name: My Portfolio CI/CD

on :
  push:
    branches: [feature/side-nav-bar]

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Setup Dart
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.1'
    
      - name: Install dependencies
        run: |
         flutter pub cache repair
         flutter clean
         flutter pub cache clean
         flutter pub upgrade
         flutter pub get

      # - name: Analyze
      #   run: flutter analyze

      - name: Build Web
        run: flutter build web --release
