name: My Portfolio CI/CD

on :
  push:
    branches: [feature/side-nav-bar]

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Create Working Directory
        run: mkdir portfolio_web

      - name: Move Files
        run: mv -v * .[^.]* portfolio_web/ || true
        working-directory: ${{ github.workspace }}
    
      - name: Setup Dart
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.1'
    
      # - name: Install dependencies
      #   run: |
      #    flutter pub cache repair
      #    flutter clean
      #    flutter pub cache clean
      #    flutter pub upgrade
      #    flutter pub get

      # - name: Analyze
      #   run: flutter analyze
      - name: List directory contents
        run: |
          ls -la
        #   cd portfolio_web/
        #   ls -la
        #   cd lib/
        #   ls -la
        #   cd pages/
        #   ls -la
        #   cat home_page.dart
        # working-directory: ${{ github.workspace }}

      - name: Build Web
        run: flutter build web
        working-directory: ${{ github.workspace }}
